services:
  form-ui:
    build:
      context: ./form-ui
    ports:
      - "4200:80"
    depends_on:
      - form-api

  form-api:
    build:
      context: ./form-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev